### ISSUE TITLE
Getting error on the module ?

### ISSUE THREAD

**Issue by ish98** [AbdullahO/tspdb#10]
removed all prior python installation and still getting this error. ? Any suggestion.

ERROR:  ModuleNotFoundError: No module named 'tspdb'
CONTEXT:  Traceback (most recent call last):
  PL/Python function "test_tspdb", line 2, in <module>
    from tspdb.src.database_module.plpy_imp import plpyimp
PL/Python function "test_tspdb"

**Comment by AbdullahO** [comment]
Hi Ish98, 

Can you give more details about the error. Which OS are you using? It seems like the python you used for installing the tspdb python package is different than thee one used by Postgres. 

By the way, if you followed the instruction in the repo, it is slightly out-of-date and has been updated just now. If you followed the instructions in the website, then it should be fine.

**Comment by ish98** [comment]
Hi Abdullah,
 I am using Windows 10. By removing the other Python versions and the environment variables, I was able to resolve the issue. I followed the installation instructions on the website. 

Thank you
Ishtiaq
