### ISSUE TITLE
ERROR:  syntax error at or near "normalize"

### ISSUE THREAD

**Issue by Toaster820** [AbdullahO/tspdb#12]
Hi,
I have this problem when I try to create the extension.

postgres=# CREATE EXTENSION tspdb;
ERROR:  syntax error at or near "normalize"
postgres=# 

 Can someone help me?
All lot thanks for your time!

**Comment by aEgoist** [comment]
me too. Is it solved now?
My environment: win10, postgreSQL 14, edb languagepack v2, PLPython3.9 

postgres=# SELECT * FROM pg_available_extensions  WHERE name LIKE '%python%' ORDER BY name;
       name        | default_version | installed_version |                  comment
-------------------+-----------------+-------------------+-------------------------------------------
 hstore_plpython2u | 1.0             |                   | transform between hstore and plpython2u
 hstore_plpython3u | 1.0             |                   | transform between hstore and plpython3u
 hstore_plpythonu  | 1.0             |                   | transform between hstore and plpythonu
 jsonb_plpython2u  | 1.0             |                   | transform between jsonb and plpython2u
 jsonb_plpython3u  | 1.0             |                   | transform between jsonb and plpython3u
 jsonb_plpythonu   | 1.0             |                   | transform between jsonb and plpythonu
 ltree_plpython2u  | 1.0             |                   | transform between ltree and plpython2u
 ltree_plpython3u  | 1.0             |                   | transform between ltree and plpython3u
 ltree_plpythonu   | 1.0             |                   | transform between ltree and plpythonu
 plpython2u        | 1.0             |                   | PL/Python2U untrusted procedural language
 plpython3u        | 1.0             | 1.0               | PL/Python3U untrusted procedural language
 plpythonu         | 1.0             |                   | PL/PythonU untrusted procedural language

**Comment by Toaster820** [comment]
Hello, the issue was that PostgreSQL has to be version 12 and not 14.

I was able to resolve the issue by just installing PostgreSQL 12 on my system.
