### ISSUE TITLE
SELECT test_tspdb();

### ISSUE THREAD

**Issue by optionsraghu** [AbdullahO/tspdb#13]
postgres=# SELECT test_tspdb();
server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.

I get the above error. Please can you help.

**Comment by AbdullahO** [comment]
Hi optionsraghu, 

for the first  problem, I think (based on discussion here: https://github.com/AbdullahO/tspdb/issues/6) that it has to do with some problems with plpython3u extension. I think he used google colab. 

For the second issue, I'm getting the same thing and will look into it. However, you can ignore that command for now since: 1- it runs correctly it just does not terminate for some reason
2- it is not essential, it is meant to test the installation. 
you can run the rest of the demo without any problems.

**Comment by luckrols** [comment]
Hi AbdullahO,

After following the installation steps for installing tspdb on Windows 11, I get the following error when doing the fist test of tspdb:

```
postgres=# SELECT test_tspdb();
ERROR:  ModuleNotFoundError: No module named 'tspdb'
CONTEXT:  Traceback (most recent call last):
  PL/Python function "test_tspdb", line 2, in <module>
    from tspdb.src.database_module.plpy_imp import plpyimp
PL/Python function "test_tspdb"
```

The second tests shows that there seem to be items missing.

D```
:\tspdb\upgrade\tspdb>psql -U postgres
Password for user postgres:
psql (12.10)
WARNING: Console code page (850) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

postgres=# SELECT * from list_pindices();
 index_name | value_columns | relation | time_column | initial_timestamp | last_timestamp | agg_interval | uncertainty_quantification
------------+---------------+----------+-------------+-------------------+----------------+--------------+----------------------------
(0 rows)
```


My PATH includes: 
...;c:\edb\languagepack\v1\Python-3.7;c:\Program Files\PostgreSQL\12\bin;c:\edb\languagepack\v1\Python-3.7\Scripts;

Then I tried to upgrade the installation, hoping that this would fix the issue, however, without success. The complete output of this is below.

How to solve this please?

Kind regards, Luc

```
**D:\tspdb>cd upgrade

D:\tspdb\upgrade>git clone https://github.com/AbdullahO/tspdb.git
Cloning into 'tspdb'...
remote: Enumerating objects: 751, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (88/88), done.R
remote: Total 751 (delta 56), reused 17 (delta 8), pack-reused 655 eceiving objects:  92% (691/751), 119.43 MiB | 24.02 MiB/s
Receiving objects: 100% (751/751), 125.24 MiB | 22.23 MiB/s, done.
Resolving deltas: 100% (465/465), done.

D:\tspdb\upgrade>cd tspdb

D:\tspdb\upgrade\tspdb>c:\edb\languagepack\v1\Python-3.7\Scripts\pip install .  --upgrade
Processing d:\tspdb\upgrade\tspdb
Requirement already satisfied, skipping upgrade: numpy in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from tspdb==0.2) (1.21.5)
Requirement already satisfied, skipping upgrade: h5py in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from tspdb==0.2) (3.6.0)
Requirement already satisfied, skipping upgrade: pandas in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from tspdb==0.2) (1.3.5)
Requirement already satisfied, skipping upgrade: sklearn in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from tspdb==0.2) (0.0)
Requirement already satisfied, skipping upgrade: scipy in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from tspdb==0.2) (1.7.3)
Requirement already satisfied, skipping upgrade: sqlalchemy in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from tspdb==0.2) (1.4.35)
Requirement already satisfied, skipping upgrade: cached-property; python_version < "3.8" in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from h5py->tspdb==0.2) (1.5.2)
Requirement already satisfied, skipping upgrade: pytz>=2017.3 in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from pandas->tspdb==0.2) (2022.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from pandas->tspdb==0.2) (2.8.2)
Requirement already satisfied, skipping upgrade: scikit-learn in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from sklearn->tspdb==0.2) (1.0.2)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from sqlalchemy->tspdb==0.2) (4.11.3)
Requirement already satisfied, skipping upgrade: greenlet!=0.4.17; python_version >= "3" and (platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))) in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from sqlalchemy->tspdb==0.2) (1.1.2)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from python-dateutil>=2.7.3->pandas->tspdb==0.2) (1.16.0)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from scikit-learn->sklearn->tspdb==0.2) (1.1.0)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from scikit-learn->sklearn->tspdb==0.2) (3.1.0)
Requirement already satisfied, skipping upgrade: typing-extensions>=3.6.4; python_version < "3.8" in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from importlib-metadata; python_version < "3.8"->sqlalchemy->tspdb==0.2) (4.1.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\edb\languagepack\v1\python-3.7\lib\site-packages (from importlib-metadata; python_version < "3.8"->sqlalchemy->tspdb==0.2) (3.8.0)
Using legacy 'setup.py install' for tspdb, since package 'wheel' is not installed.
Installing collected packages: tspdb
  Attempting uninstall: tspdb
    Found existing installation: tspdb 0.2
    Uninstalling tspdb-0.2:
      Successfully uninstalled tspdb-0.2
    Running setup.py install for tspdb ... done
Successfully installed tspdb-0.2

D:\tspdb\upgrade\tspdb>robocopy /s extension_py3  "c:\Program Files\PostgreSQL\12\share\extension"

-------------------------------------------------------------------------------
   ROBOCOPY     ::     Robust File Copy for Windows
-------------------------------------------------------------------------------

  Started : Friday, 8 April, 2022 09:42:56
   Source : D:\tspdb\upgrade\tspdb\extension_py3\
     Dest : c:\Program Files\PostgreSQL\12\share\extension\

    Files : *.*

  Options : *.* /S /DCOPY:DA /COPY:DAT /R:1000000 /W:30

------------------------------------------------------------------------------

                           3    D:\tspdb\upgrade\tspdb\extension_py3\
          *EXTRA File                274        adminpack--1.0--1.1.sql
          *EXTRA File               1535        adminpack--1.0.sql
          *EXTRA File               1682        adminpack--1.1--2.0.sql
          *EXTRA File                176        adminpack.control
          *EXTRA File                931        amcheck--1.0--1.1.sql
          *EXTRA File                704        amcheck--1.0.sql
          *EXTRA File                705        amcheck--1.1--1.2.sql
          *EXTRA File                154        amcheck.control
          *EXTRA File                249        autoinc--1.0.sql
          *EXTRA File                250        autoinc--unpackaged--1.0.sql
          *EXTRA File                149        autoinc.control
          *EXTRA File                666        bloom--1.0.sql
          *EXTRA File                156        bloom.control
          *EXTRA File               1372        btree_gin--1.0--1.1.sql
          *EXTRA File              24818        btree_gin--1.0.sql
          *EXTRA File               1445        btree_gin--1.1--1.2.sql
          *EXTRA File               4571        btree_gin--1.2--1.3.sql
          *EXTRA File              10107        btree_gin--unpackaged--1.0.sql
          *EXTRA File                160        btree_gin.control
          *EXTRA File               3739        btree_gist--1.0--1.1.sql
          *EXTRA File               5048        btree_gist--1.1--1.2.sql
          *EXTRA File               1955        btree_gist--1.2--1.3.sql
          *EXTRA File              41115        btree_gist--1.2.sql
          *EXTRA File               1932        btree_gist--1.3--1.4.sql
          *EXTRA File               1872        btree_gist--1.4--1.5.sql
          *EXTRA File              21479        btree_gist--unpackaged--1.0.sql
          *EXTRA File                163        btree_gist.control
          *EXTRA File               1028        citext--1.0--1.1.sql
          *EXTRA File               3424        citext--1.1--1.2.sql
          *EXTRA File                850        citext--1.2--1.3.sql
          *EXTRA File                668        citext--1.3--1.4.sql
          *EXTRA File               2284        citext--1.4--1.5.sql
          *EXTRA File              13466        citext--1.4.sql
          *EXTRA File                427        citext--1.5--1.6.sql
          *EXTRA File              10352        citext--unpackaged--1.0.sql
          *EXTRA File                158        citext.control
          *EXTRA File               1594        cube--1.0--1.1.sql
          *EXTRA File               3815        cube--1.1--1.2.sql
          *EXTRA File                365        cube--1.2--1.3.sql
          *EXTRA File               9761        cube--1.2.sql
          *EXTRA File               2387        cube--1.3--1.4.sql
          *EXTRA File               3195        cube--unpackaged--1.0.sql
          *EXTRA File                142        cube.control
          *EXTRA File                419        dblink--1.0--1.1.sql
          *EXTRA File               2832        dblink--1.1--1.2.sql
          *EXTRA File               6645        dblink--1.2.sql
          *EXTRA File               2863        dblink--unpackaged--1.0.sql
          *EXTRA File                170        dblink.control
          *EXTRA File                711        dict_int--1.0.sql
          *EXTRA File                493        dict_int--unpackaged--1.0.sql
          *EXTRA File                158        dict_int.control
          *EXTRA File                694        dict_xsyn--1.0.sql
          *EXTRA File                488        dict_xsyn--unpackaged--1.0.sql
          *EXTRA File                179        dict_xsyn.control
          *EXTRA File                671        earthdistance--1.0--1.1.sql
          *EXTRA File               3234        earthdistance--1.1.sql
          *EXTRA File                959        earthdistance--unpackaged--1.0.sql
          *EXTRA File                202        earthdistance.control
          *EXTRA File                475        file_fdw--1.0.sql
          *EXTRA File                155        file_fdw.control
          *EXTRA File                788        fuzzystrmatch--1.0--1.1.sql
          *EXTRA File               1576        fuzzystrmatch--1.1.sql
          *EXTRA File               1108        fuzzystrmatch--unpackaged--1.0.sql
          *EXTRA File                175        fuzzystrmatch.control
          *EXTRA File                279        hstore--1.0--1.1.sql
          *EXTRA File               1639        hstore--1.1--1.2.sql
          *EXTRA File                525        hstore--1.2--1.3.sql
          *EXTRA File               5310        hstore--1.3--1.4.sql
          *EXTRA File                409        hstore--1.4--1.5.sql
          *EXTRA File              13765        hstore--1.4.sql
          *EXTRA File                455        hstore--1.5--1.6.sql
          *EXTRA File               5509        hstore--unpackaged--1.0.sql
          *EXTRA File                158        hstore.control
          *EXTRA File                580        hstore_plperl--1.0.sql
          *EXTRA File                186        hstore_plperl.control
          *EXTRA File                627        hstore_plperlu--1.0.sql
          *EXTRA File                189        hstore_plperlu.control
          *EXTRA File                750        hstore_plpython2u--1.0.sql
          *EXTRA File                201        hstore_plpython2u.control
          *EXTRA File                750        hstore_plpython3u--1.0.sql
          *EXTRA File                201        hstore_plpython3u.control
          *EXTRA File                698        hstore_plpythonu--1.0.sql
          *EXTRA File                198        hstore_plpythonu.control
          *EXTRA File                273        insert_username--1.0.sql
          *EXTRA File                282        insert_username--unpackaged--1.0.sql
          *EXTRA File                170        insert_username.control
          *EXTRA File                897        intagg--1.0--1.1.sql
          *EXTRA File               1089        intagg--1.1.sql
          *EXTRA File                468        intagg--unpackaged--1.0.sql
          *EXTRA File                119        intagg.control
          *EXTRA File               1794        intarray--1.0--1.1.sql
          *EXTRA File               5525        intarray--1.1--1.2.sql
          *EXTRA File              12293        intarray--1.2.sql
          *EXTRA File               7274        intarray--unpackaged--1.0.sql
          *EXTRA File                176        intarray.control
          *EXTRA File              12333        isn--1.0--1.1.sql
          *EXTRA File               5264        isn--1.1--1.2.sql
          *EXTRA File              69885        isn--1.1.sql
          *EXTRA File              23705        isn--unpackaged--1.0.sql
          *EXTRA File                160        isn.control
          *EXTRA File                658        jsonb_plperl--1.0.sql
          *EXTRA File                176        jsonb_plperl.control
          *EXTRA File                702        jsonb_plperlu--1.0.sql
          *EXTRA File                178        jsonb_plperlu.control
          *EXTRA File                732        jsonb_plpython2u--1.0.sql
          *EXTRA File                191        jsonb_plpython2u.control
          *EXTRA File                732        jsonb_plpython3u--1.0.sql
          *EXTRA File                191        jsonb_plpython3u.control
          *EXTRA File                682        jsonb_plpythonu--1.0.sql
          *EXTRA File                188        jsonb_plpythonu.control
          *EXTRA File                223        lo--1.0--1.1.sql
          *EXTRA File                722        lo--1.1.sql
          *EXTRA File                314        lo--unpackaged--1.0.sql
          *EXTRA File                126        lo.control
          *EXTRA File               6336        ltree--1.0--1.1.sql
          *EXTRA File              19375        ltree--1.1.sql
          *EXTRA File               7998        ltree--unpackaged--1.0.sql
          *EXTRA File                155        ltree.control
          *EXTRA File                449        ltree_plpython2u--1.0.sql
          *EXTRA File                197        ltree_plpython2u.control
          *EXTRA File                449        ltree_plpython3u--1.0.sql
          *EXTRA File                197        ltree_plpython3u.control
          *EXTRA File                423        ltree_plpythonu--1.0.sql
          *EXTRA File                194        ltree_plpythonu.control
          *EXTRA File                261        moddatetime--1.0.sql
          *EXTRA File                266        moddatetime--unpackaged--1.0.sql
          *EXTRA File                165        moddatetime.control
          *EXTRA File                560        pageinspect--1.0--1.1.sql
          *EXTRA File                562        pageinspect--1.1--1.2.sql
          *EXTRA File               1946        pageinspect--1.2--1.3.sql
          *EXTRA File               2566        pageinspect--1.3--1.4.sql
          *EXTRA File               1347        pageinspect--1.4--1.5.sql
          *EXTRA File               2252        pageinspect--1.5--1.6.sql
          *EXTRA File               6262        pageinspect--1.5.sql
          *EXTRA File                698        pageinspect--1.6--1.7.sql
          *EXTRA File               1116        pageinspect--unpackaged--1.0.sql
          *EXTRA File                173        pageinspect.control
          *EXTRA File                307        pgcrypto--1.0--1.1.sql
          *EXTRA File                483        pgcrypto--1.1--1.2.sql
          *EXTRA File               2346        pgcrypto--1.2--1.3.sql
          *EXTRA File               5708        pgcrypto--1.3.sql
          *EXTRA File               2449        pgcrypto--unpackaged--1.0.sql
          *EXTRA File                137        pgcrypto.control
          *EXTRA File                651        pgrowlocks--1.0--1.1.sql
          *EXTRA File                253        pgrowlocks--1.1--1.2.sql
          *EXTRA File                555        pgrowlocks--1.2.sql
          *EXTRA File                273        pgrowlocks--unpackaged--1.0.sql
          *EXTRA File                152        pgrowlocks.control
          *EXTRA File                400        pgstattuple--1.0--1.1.sql
          *EXTRA File               1435        pgstattuple--1.1--1.2.sql
          *EXTRA File               1126        pgstattuple--1.2--1.3.sql
          *EXTRA File                623        pgstattuple--1.3--1.4.sql
          *EXTRA File               5506        pgstattuple--1.4--1.5.sql
          *EXTRA File               3764        pgstattuple--1.4.sql
          *EXTRA File                457        pgstattuple--unpackaged--1.0.sql
          *EXTRA File                147        pgstattuple.control
          *EXTRA File                508        pg_buffercache--1.0--1.1.sql
          *EXTRA File                271        pg_buffercache--1.1--1.2.sql
          *EXTRA File                328        pg_buffercache--1.2--1.3.sql
          *EXTRA File                794        pg_buffercache--1.2.sql
          *EXTRA File                351        pg_buffercache--unpackaged--1.0.sql
          *EXTRA File                157        pg_buffercache.control
          *EXTRA File                335        pg_freespacemap--1.0--1.1.sql
          *EXTRA File                377        pg_freespacemap--1.1--1.2.sql
          *EXTRA File                899        pg_freespacemap--1.1.sql
          *EXTRA File                375        pg_freespacemap--unpackaged--1.0.sql
          *EXTRA File                160        pg_freespacemap.control
          *EXTRA File                281        pg_prewarm--1.0--1.1.sql
          *EXTRA File                458        pg_prewarm--1.1--1.2.sql
          *EXTRA File                475        pg_prewarm--1.1.sql
          *EXTRA File                139        pg_prewarm.control
          *EXTRA File               1246        pg_stat_statements--1.0--1.1.sql
          *EXTRA File               1336        pg_stat_statements--1.1--1.2.sql
          *EXTRA File               1454        pg_stat_statements--1.2--1.3.sql
          *EXTRA File                345        pg_stat_statements--1.3--1.4.sql
          *EXTRA File                305        pg_stat_statements--1.4--1.5.sql
          *EXTRA File               1427        pg_stat_statements--1.4.sql
          *EXTRA File                376        pg_stat_statements--1.5--1.6.sql
          *EXTRA File                806        pg_stat_statements--1.6--1.7.sql
          *EXTRA File                449        pg_stat_statements--unpackaged--1.0.sql
          *EXTRA File                191        pg_stat_statements.control
          *EXTRA File                536        pg_trgm--1.0--1.1.sql
          *EXTRA File               2192        pg_trgm--1.1--1.2.sql
          *EXTRA File               3498        pg_trgm--1.2--1.3.sql
          *EXTRA File               2045        pg_trgm--1.3--1.4.sql
          *EXTRA File               7975        pg_trgm--1.3.sql
          *EXTRA File               4689        pg_trgm--unpackaged--1.0.sql
          *EXTRA File                177        pg_trgm.control
          *EXTRA File                883        pg_visibility--1.0--1.1.sql
          *EXTRA File                833        pg_visibility--1.1--1.2.sql
          *EXTRA File               2825        pg_visibility--1.1.sql
          *EXTRA File                186        pg_visibility.control
          *EXTRA File               2511        pldbgapi--1.0--1.1.sql
          *EXTRA File               7460        pldbgapi--1.1.sql
          *EXTRA File               2259        pldbgapi--unpackaged--1.1.sql
          *EXTRA File                181        pldbgapi.control
          *EXTRA File                301        plperl--1.0.sql
          *EXTRA File                356        plperl--unpackaged--1.0.sql
          *EXTRA File                176        plperl.control
          *EXTRA File                315        plperlu--1.0.sql
          *EXTRA File                365        plperlu--unpackaged--1.0.sql
          *EXTRA File                187        plperlu.control
          *EXTRA File                310        plpgsql--1.0.sql
          *EXTRA File                370        plpgsql--unpackaged--1.0.sql
          *EXTRA File                179        plpgsql.control
          *EXTRA File                329        plpython2u--1.0.sql
          *EXTRA File                391        plpython2u--unpackaged--1.0.sql
          *EXTRA File                196        plpython2u.control
          *EXTRA File                329        plpython3u--1.0.sql
          *EXTRA File                391        plpython3u--unpackaged--1.0.sql
          *EXTRA File                196        plpython3u.control
          *EXTRA File                325        plpythonu--1.0.sql
          *EXTRA File                382        plpythonu--unpackaged--1.0.sql
          *EXTRA File                194        plpythonu.control
          *EXTRA File                294        pltcl--1.0.sql
          *EXTRA File                220        pltcl--unpackaged--1.0.sql
          *EXTRA File                173        pltcl.control
          *EXTRA File                308        pltclu--1.0.sql
          *EXTRA File                225        pltclu--unpackaged--1.0.sql
          *EXTRA File                184        pltclu.control
          *EXTRA File                507        postgres_fdw--1.0.sql
          *EXTRA File                172        postgres_fdw.control
          *EXTRA File                343        refint--1.0.sql
          *EXTRA File                314        refint--unpackaged--1.0.sql
          *EXTRA File                169        refint.control
          *EXTRA File               3005        seg--1.0--1.1.sql
          *EXTRA File                360        seg--1.1--1.2.sql
          *EXTRA File               8142        seg--1.1.sql
          *EXTRA File               2344        seg--1.2--1.3.sql
          *EXTRA File               2782        seg--unpackaged--1.0.sql
          *EXTRA File                172        seg.control
          *EXTRA File                375        sslinfo--1.0--1.1.sql
          *EXTRA File                746        sslinfo--1.1--1.2.sql
          *EXTRA File               1534        sslinfo--1.2.sql
          *EXTRA File                846        sslinfo--unpackaged--1.0.sql
          *EXTRA File                146        sslinfo.control
          *EXTRA File               2153        tablefunc--1.0.sql
          *EXTRA File               1160        tablefunc--unpackaged--1.0.sql
          *EXTRA File                174        tablefunc.control
          *EXTRA File                274        tcn--1.0.sql
          *EXTRA File                134        tcn.control
          *EXTRA File                406        test_bloomfilter--1.0.sql
          *EXTRA File                135        test_bloomfilter.control
          *EXTRA File                197        test_ext1--1.0.sql
          *EXTRA File                127        test_ext1.control
          *EXTRA File                197        test_ext2--1.0.sql
          *EXTRA File                105        test_ext2.control
          *EXTRA File                339        test_ext3--1.0.sql
          *EXTRA File                 72        test_ext3.control
          *EXTRA File                197        test_ext4--1.0.sql
          *EXTRA File                 95        test_ext4.control
          *EXTRA File                197        test_ext5--1.0.sql
          *EXTRA File                 72        test_ext5.control
          *EXTRA File                 45        test_ext6--1.0.sql
          *EXTRA File                104        test_ext6.control
          *EXTRA File                305        test_ext7--1.0--2.0.sql
          *EXTRA File                518        test_ext7--1.0.sql
          *EXTRA File                 91        test_ext7.control
          *EXTRA File                680        test_ext8--1.0.sql
          *EXTRA File                 91        test_ext8.control
          *EXTRA File                211        test_ext_cyclic1--1.0.sql
          *EXTRA File                109        test_ext_cyclic1.control
          *EXTRA File                211        test_ext_cyclic2--1.0.sql
          *EXTRA File                109        test_ext_cyclic2.control
          *EXTRA File                309        test_integerset--1.0.sql
          *EXTRA File                124        test_integerset.control
          *EXTRA File               2254        test_pg_dump--1.0.sql
          *EXTRA File                 86        test_pg_dump.control
          *EXTRA File                491        test_predtest--1.0.sql
          *EXTRA File                137        test_predtest.control
          *EXTRA File                308        test_rbtree--1.0.sql
          *EXTRA File                132        test_rbtree.control
          *EXTRA File                327        tsm_system_rows--1.0.sql
          *EXTRA File                186        tsm_system_rows.control
          *EXTRA File                327        tsm_system_time--1.0.sql
          *EXTRA File                192        tsm_system_time.control
          *EXTRA File                445        unaccent--1.0--1.1.sql
          *EXTRA File                910        unaccent--1.1.sql
          *EXTRA File                766        unaccent--unpackaged--1.0.sql
          *EXTRA File                157        unaccent.control
          *EXTRA File                688        uuid-ossp--1.0--1.1.sql
          *EXTRA File               1516        uuid-ossp--1.1.sql
          *EXTRA File                853        uuid-ossp--unpackaged--1.0.sql
          *EXTRA File                163        uuid-ossp.control
          *EXTRA File                944        xml2--1.0--1.1.sql
          *EXTRA File               2049        xml2--1.1.sql
          *EXTRA File               1341        xml2--unpackaged--1.0.sql
          *EXTRA File                208        xml2.control
100%        Newer                    202        Makefile
100%        Newer                  11742        tspdb--0.0.1.sql
100%        Newer                     83        tspdb.control

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         1         0         1         0         0         0
   Files :         3         3         0         0         0       288
   Bytes :    11.7 k    11.7 k         0         0         0   557.7 k
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00


   Speed :             4009000 Bytes/sec.
   Speed :             229.397 MegaBytes/min.
   Ended : Friday, 8 April, 2022 09:42:56


D:\tspdb\upgrade\tspdb>psql -U postgres
Password for user postgres:
psql (12.10)
WARNING: Console code page (850) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

postgres=# DROP EXTENSION tspdb CASCADE;
DROP EXTENSION
postgres=# CREATE EXTENSION tspdb;
CREATE EXTENSION
postgres=# SELECT test_tspdb();
ERROR:  ModuleNotFoundError: No module named 'tspdb'
CONTEXT:  Traceback (most recent call last):
  PL/Python function "test_tspdb", line 2, in <module>
    from tspdb.src.database_module.plpy_imp import plpyimp
PL/Python function "test_tspdb"**
```

**Comment by optionsraghu** [comment]
> Hi optionsraghu,
> 
> for the first problem, I think (based on discussion here: #6) that it has to do with some problems with plpython3u extension. I think he used google colab.
> 
> For the second issue, I'm getting the same thing and will look into it. However, you can ignore that command for now since: 1- it runs correctly it just does not terminate for some reason 2- it is not essential, it is meant to test the installation. you can run the rest of the demo without any problems.

Thank you Abdullah. I will move on beyond the test db.

**Comment by AbdullahO** [comment]
hi @luckrols , 

This error indicates that you have installed the python package of tspDB on another python engine; different than the one used by postgres. See this issue and the comments therein: https://github.com/AbdullahO/tspdb/issues/11 

feel free to reopen that issue if things don't workout.
