### ISSUE TITLE
I can install tspdb successfully,but I can't use it test example

### ISSUE THREAD

**Issue by tianatian** [AbdullahO/tspdb#14]
everything is ok,but when i run "select test_tspdb();",it always shows Server Disconnected.Is there something I didn't do well？

**Comment by AbdullahO** [comment]
This seems to be similar to issue https://github.com/AbdullahO/tspdb/issues/6, it seems that plpython3u support for windows is faulty, which is something I cannot fix. I'm going to create a docker image soon to make installation easier.

**Comment by zarif98sjs** [comment]
Hi @AbdullahO , did you make any docker image? I can't seem to find any.
