### ISSUE TITLE
Unsatisfactory forecast results

### ISSUE THREAD

**Issue by lesmesrafa** [AbdullahO/tspdb#17]
Hi, I was testing this tool to forecast 10 time series, however, in none of the predictions I did I can't consider that the tool returns satisfactory results (Considering that in the examples ([notebook_examples/tspDB Example-Multiple Time Series (Real-world Data).ipynb](https://github.com/AbdullahO/tspdb/blob/b40e6b783ddf5d21fb814cab071aca245ecf65f5/notebook_examples/tspDB%20Example-Multiple%20Time%20Series%20(Real-world%20Data).ipynb)] almost all time series achieve good results).  Below you can see some screenshots of the results I have obtained for each time series. The screenshots have been obtained from the following datasets:

- [tmpseries.csv](https://github.com/AbdullahO/tspdb/files/8587442/tmpseries.csv)
- [tmpseries2.csv](https://github.com/AbdullahO/tspdb/files/8587447/tmpseries2.csv)

The following images have been obtained from [tmpseries.csv](https://github.com/AbdullahO/tspdb/files/8587442/tmpseries.csv) and all of them have been obtained predicting between 8 and 14 days in the future:

1. Time Series A:
![6daysaheadA](https://user-images.githubusercontent.com/58077392/165869467-b3dac840-7756-4fdd-a664-bc755af82972.png)
2. Time Series B:
![6daysaheadB](https://user-images.githubusercontent.com/58077392/165869535-c887f5b9-c400-4fb2-bae5-993d161cf1f6.png)
3. Time Series C:
![8daysaheadC](https://user-images.githubusercontent.com/58077392/165869607-a7cdf40b-b517-4c76-a110-c97a0aa87929.png)
4. Time Series D:
![D](https://user-images.githubusercontent.com/58077392/165869635-7395b6f3-5945-453c-9010-a013acc8e349.png)
5. Time Series E:
![8daysaheadE](https://user-images.githubusercontent.com/58077392/165869662-6c03c13b-4eac-4e04-a07a-215622a34029.png)
6. Time Series F:
![daysaheadF](https://user-images.githubusercontent.com/58077392/165869712-f754fba0-f229-4551-a920-4175fb7e8fc4.png)
7. Time Series G:
![G](https://user-images.githubusercontent.com/58077392/165869728-65d4d33e-c957-4501-8569-5473042aaff2.png)
8. Time Series H:
![H](https://user-images.githubusercontent.com/58077392/165869746-ac7739eb-e47e-489c-81c6-e6abec42045a.png)
9. Time Series I:
![I](https://user-images.githubusercontent.com/58077392/165869813-3a423f01-0673-43cf-87fb-424d4a5d80f4.png)

These results were obtained as shown in the following .ipynb:
[codemultipleTS.zip](https://github.com/AbdullahO/tspdb/files/8587518/codemultipleTS.zip)

The following images have been obtained from [tmpseries2.csv](https://github.com/AbdullahO/tspdb/files/8587521/tmpseries2.csv). The first image corresponds to a one-month forecast and the second image to a 10-day forecast.

1. Time Series one month ahead:
![1monthaheadTMPSeries2](https://user-images.githubusercontent.com/58077392/165870666-d72cb87e-8e30-4f3e-9e27-3a28beb9efe6.png)
2. Time Series 10 days ahead:
![10daysaheadTMPSeries2](https://user-images.githubusercontent.com/58077392/165870688-f172c3c6-e922-4367-bbca-564b0faba540.png)

These results have been obtained using the same code as the previous predictions (evidently changing the dataset path, the prediction dates and the distribution of the data in the training data (80% of the dataset) and test data (20% of the dataset).

Does anyone else get the same results/or have the same problem with other time series? Or am I using this tool wrong?

I obtained these results with the following software versions:

- Ubuntu 20.04.1
- PostgreSQL 12.10
- Python 3.9

**Comment by AbdullahO** [comment]
Hey @lesmesrafa, 

Thanks for the feedback. It is possible that the tool may not provide satisfactory results for some time series.  Though I think one thing that would help a lot is playing around with the hyperparameter k (see API reference here: https://tspdb.mit.edu/API/ )

This hyperparameter control the complexity of your model; the higher it is the higher the complexity. By default, it is selected in a data-driven way that often works well,  but for some time series it is important to tune it. For example, you can set k to, e.g., 3 using the query (an adjusted form of the query from your notebook)

```
select create_pindex('ts_pred', 'Date','"""+columns+"""','pindex1', k =>3);
```

Another potential problem, which I think is probable from looking at the second dataset,  is that your time series has a change-point. i.e., its underlying process changes and hence you are fitting data from different "regimes".  See our work [here](https://github.com/ArwaAlanqary/mSSA_cpd) and the associated paper [here](https://openreview.net/forum?id=i0DmV60aeK).

**Comment by suhanovs** [comment]
@lesmesrafa I was getting similar results to your time series one month ahead chart, until I realized that the algorithm is to add newly observed data points to the dataset you use to make predictions. So the algorithm is as follows: 

1. Build an index on dataset up to time T. Use the setting to prevent automatic pindex update.
2. Predict T+1 and decide if you want to act on it
3. When T+1 is observed, write it to the dataset 
4. Predict T+2 (with T+1 in the dataset) and decide if you want to act on T+2 prediction
5. When T+2 is observed, write it... and so on

This is apparent if you look at this https://colab.research.google.com/drive/1yA3gMVB3XxKYgnSKx0O5dTWMElfX8J2S?usp=sharing#scrollTo=X4n3Eho-zStu, scenario III.

Then you get something more along the lines of this: 

![image](https://user-images.githubusercontent.com/21265876/165881968-6a70dc97-2d78-4aab-88f7-fb52326b065a.png)

But as I start to review my test results, I am also starting to wonder how to apply this, if it could work better on different time periods or different instrument, etc. I am finding predictions to be lagging similar to <pick your favourite lagging indicator>.

**Comment by suhanovs** [comment]
@AbdullahO  Thank you for confirming this.

**Comment by arpieb** [comment]
@AbdullahO confirming I'm reading the above correctly - if I say predict multistep ahead for 10 days, day t+10 doesn't incorporate t+1..t+9 forecasts in its predictions unless they are written to the database t+1 at a time?

**Comment by AbdullahO** [comment]
It absolutely does. What @suhanovs  is referring to how you can do 1-step ahead forecasts over a long period; which basically goes as he described.

**Comment by lesmesrafa** [comment]
@AbdullahO @suhanovs in the algorithm you say (https://colab.research.google.com/drive/1yA3gMVB3XxKYgnSKx0O5dTWMElfX8J2S?usp=sharing#scrollTo=X4n3Eho-zStu scenario III), what do you insert in the dataset: the test samples (i in the loop of the code you mention) or the predictions made with predict query?

I say this because if I insert in the dataset the samples of the test dataset (i) I get results similar to yours, however, in real life you don't have the test dataset (for example if I want to predict time series A for May 4, 2022, I couldn't because I don't have data up to that date). On the other hand, if I insert the predictions made (something that would make sense in a real application) I don't obtain good results.

**Comment by AbdullahO** [comment]
- If you need to forecast one month in advance, then what you did in the first post is the right thing to do; the forecast performance may be enhanced by changing the parameter `k`
- if you only want to do some k-steps forecast for some k, and you want to evaluate the tool. Then you should follow scenario 3 in the colab. Assume you want to forecast the period T+1 to t+Nk for some integer N . Then you do:
1. forecast the time series from T+1 to T+k
2. insert the actual test samples at time T+1 to T+k to the DB
3. forecast  the time series from T+k+1 to T+2k
4. insert the actual test samples at time T+k+1 to T+2k to the DB
.. and so on and so forth

**Comment by suhanovs** [comment]
@lesmesrafa I don't know if I agree that in real life you don't have the dataset that we refer to as "test dataset" here.  To use your example of May 4, you can make a prediction for May 4 using data that you have today on April 30. When you get May 1 data, you add it to your dataset and revise prediction you made for May 4. The closer you get to May 4, the more data you will have on hand, and the more accurate your prediction becomes (which follows from what @AbdullahO shared with us that predictions built on predictions being less accurate).

@AbdullahO Thanks for the 'k' hint.
